
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 11 11:41:39 NZDT 2009
//----------------------------------------------------

// package weka.core.mathematicalexpression;

/** CUP generated interface containing symbol constants. */
class sym {
  /* terminals */
public:
  const static int TIMES = 7;
  const static int AND = 29;
  const static int IFELSE = 20;
  const static int LT = 23;
  const static int SIN = 13;
  const static int PLUS = 6;
  const static int OR = 30;
  const static int RPAREN = 4;
  const static int COS = 14;
  const static int DIVISION = 8;
  const static int NOT = 28;
  const static int POW = 18;
  const static int SQRT = 10;
  const static int VARIABLE = 33;
  const static int TRUE = 21;
  const static int FLOOR = 17;
  const static int RINT = 16;
  const static int GT = 25;
  const static int CEIL = 19;
  const static int LPAREN = 3;
  const static int LE = 24;
  const static int LOG = 11;
  const static int EXP = 12;
  const static int BOOLEAN = 32;
  const static int COMMA = 2;
  const static int NUMBER = 31;
  const static int EOF = 0;
  const static int ABS = 9;
  const static int GE = 26;
  const static int FALSE = 22;
  const static int MINUS = 5;
  const static int error = 1;
  const static int EQ = 27;
  const static int TAN = 15;
};

